### ISSUE TITLE
Linux でうまく動作しない

### ISSUE THREAD

**Issue by mooz** [to/tombloo#10]
Ubuntu 9.04 において Firefox 3.5, 3.6 へ Tombloo をインストールし動作を確認したのですが、
次のような問題が生じています
- コンテンツエリアのコンテキストメニューで "Share(J)" をクリックしても反応が無い
- コンテキストメニューで "Share", "Tombloo" などのサブメニューが空
- ツールバー -> Tombloo も同様に空
- 設定画面で「デフォルトのポスト先」が空

エラーコンソールにて以下のエラーを確認しました。

エラー: uncaught exception: [Exception... "Component returned failure code: 0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE) [nsIJSCID.getService]"  nsresult: "0x80570016 (NS_ERROR_XPC_GS_RETURNED_FAILURE)"  location: "JS frame :: chrome://tombloo/content/browser.xul :: anonymous :: line 32"  data: no]

ご対応頂ければと思います。

**Comment by to** [comment]
僕はLinux使ってないからわからないんですが…。
ここらへんが関係あるのかもしれません。

http://wiki.mozilla.gr.jp/wiki.cgi?page=BugTrack-Fx3%2F56
http://www.mail-archive.com/freebsd-users-jp@jp.freebsd.org/msg03542.html

**Comment by mooz** [comment]
ありがとうございます。

さきほど、原因が判明したしました。以下に原因と再現方法を載せておきます。

実体が HTML で無いのに URL の末尾が .js で終わるようなリンク  (GitHub の blob など) 上で右クリックをし、 Tombloo パッチをインストールを選択します。

すると、 ProfD/tombloo/script 以下に HTML ファイルがパッチとしてインストールされてしまいます。

このため Tombloo が起動時にパッチを読み込むところでこけ、初期化に失敗していた様子です。

こんなアホなことをやらかす輩は僕の他に余りいないとは思うのですが、万が一を考えてパッチ読み込み処理に生じる例外は処理しておいた方が良いかと思います。

お騒がせ致しました。

**Comment by to** [comment]
あーなるほどー。
なにか対策できそうですね。
検討してみますー。

**Comment by to** [comment]
とりあえず簡易チェックを追加。

http://github.com/to/tombloo/commit/acf130c60e2411e74c41151415f72eeb5af2b9f1

ほんとはextractorみたいにrawを探してきてほしい。
そうすればパッチディレクトリからそのままダイレクトにインストールできる。
