### ISSUE TITLE
Amazon API の変更への対応

### ISSUE THREAD

**Issue by whym** [to/tombloo#2]
こちらでも触れられてますが、
http://d.hatena.ne.jp/zorio/20090509/1241886502
Amazon の API では、２００９年8月15日から、リクエスト文字列を秘密鍵でハッシュした値を渡さないといけなくなったようです。

秘密鍵はソースに書いてはいけないので、API使うのをやめて、HTMLから取るしかないんじゃないかと思います。

↓その場しのぎのパッチ
http://gist.github.com/173074

**Comment by to** [comment]
HTMLから取得するようにしました!

http://github.com/to/tombloo/commit/196c5b1d87d36f1302657fe885fb261adb23bf14
