### ISSUE TITLE
Firefox4.0正式版が正常に起動しなくなる

### ISSUE THREAD

**Issue by lunabahamut** [to/tombloo#21]
tombloo0.4.20及び0.4.19で確認。
tomblooインストール後、Firefox4.0正式版が正常に起動しなくなる。
プロセスは残っているようだが、ウインドウは開かないままである。

0.4.17を強制的にインストールしたところ、正常に起動したが、右クリックメニュー及び設定画面が開かない。

**Comment by to** [comment]
うーん、Twitter見てても起動できない人がいるみたいですね。
他の拡張やOSなどの環境依存の問題かもしれません。
衝突の可能性のある拡張はインストールされていますか?　Macですか? 新しいプロファイルでも発生しますか?
Ctrl + Shift + Jで表示されるエラーコンソールにエラーが出るんですが、起動しないと無理ですよね…。

**Comment by to** [comment]
Tomblooコンポーネントの登録が異常になっているのかもしれません。
一度、Tomblooをアンインストール後、Firefoxを再起動し、もう一度インストールすると直るかもしれません。
あとTomblooパッチのいずれかが干渉している可能性もありそうです。

**Comment by iwadon** [comment]
手元の環境(iMac、Mac OS X 10.6.7、Firefox 4.0、Tombloo 0.4.20)では、Stylish 1.1.1を無効にすることでTomblooを有効にしたままウィンドウを表示できるようになりました。確証はありませんが念の為ご報告します。
あと、Ctrl+Shift+J(MacだとCommand+Shift+J)はウィンドウが出ないとメニューにも出ないため入力できませんでした。

**Comment by lunabahamut** [comment]
申し訳ございません、競合してるアドオンを調査したつもりだったのですが、ミスがあったようです・・・。
ただ今、私の環境（Windows7 64bit,Firefox4.0,tombloo0.4.20）で①新規プロファイル作成後、tomblooのみインストール ②私の既存のプロファイルで各種アドオンとの競合の再調査 をしたところ、「Stylish1.1.1」が競合していたようです。
上の方が仰っているように、「Stylish1.1.1」を無効にすることでtomblooが下記の点を除いて正常に使えるようになりました。

・tomblooの設定ウインドウを閉じる（右クリックメニュー、アドオンマネージャのどちらから開いたものでも）と、Firefox自体のウインドウが閉じられてしまう

**Comment by to** [comment]
了解ですー、チェックしてみます。ありがとうございましたー。

**Comment by rnd0** [comment]
I confirm 2 issues with tombloo 0.4.20 and firefox 4.0 (on Windows 7 and Ubuntu 10.10):
1. Tombloo conflicts with stylish 1.1.1 — if both of them installed, Firefox 4 does not open.
2. When I close tombloo preference window by clicking [x], it closes firefox. Closing with «Close» button works normally.

**Comment by to** [comment]
http://gyazo.com/9a845abba3c8f8f4906044a568453286.png

Stylish1.1.1、インストールしてみたんですが、再現しませんでした!!!
設定ウィンドウの閉じるボタンの件は、別バグっぽいすね。
うーん。起動しないって、よっぽどだよなあ。

**Comment by to** [comment]
http://twitter.com/#!/anamorphobia/statuses/50541817573277696

Stylish設定を作り直して復旧したとのこと。
Stylishを有効で、Tombloo無効なら起動するんですか???

**Comment by iwadon** [comment]
起動しないというか、ウィンドウが表示されないんですよね。
ウィンドウメニューを見るとたしかにウィンドウが存在するのですが、
画面には出てこないという。例えば履歴からYouTubeの動画ページを選ぶと
動画が再生されますが、ウィンドウは表示されず音だけ聞こえます。
ただし、ダウンロード(Command+J)やFirefoxについてなどは表示できます。
Stylishの設定作り直しはこれから試してみます。

うまく動かない様子を動画にしました: http://tumblr.com/x3w1uxgm0m

**Comment by to** [comment]
ビデオ、よくわかりました。
エラーコンソールメニューがないって、すごく変なところでストップしてますよね。
stylish.sqliteがあると、エラーを再現し修正できるかもしれません。
ちょっと推測むずかしいです。ブラウザを変えるスタイルとバッティングしてるような気もするんですが。

**Comment by iwadon** [comment]
http://moonrock.jp/~don/stylish.sqlite-20110324.zip
現状(うまく動かない状態)でのstylish.sqliteを用意しましたので、
よろしければお使いください。ユーザスタイルが5つ入っています。

**Comment by to** [comment]
すいません、リンクが切れてるみたいです…。

**Comment by syota** [comment]
Firefox 4.0+Tombloo 0.4.20+Stylish 1.1.1で起動しない件、再現できました。
Tombloo 0.4.20とStylish 1.1.1が競合しているわけではなく、Stylishのスタイルが原因のようです。

StylishでFirefoxのコンテキストメニュー(右クリックのメニュー)を操作するスタイルを有効にすると再現します。

例えば、Stylishでこんな感じのスタイルを有効にすると起動しません。

<pre><code>#context-back {
    /* コンテキストメニュー「戻る」を非表示にする */
    display: none !important;
}</code></pre>


正常に起動させるにはstylish.sqliteを削除しなければならないので注意してください。

**Comment by to** [comment]
スタイルが一つでもあると、エラーになるんですね。
直し方わかりました!! Tombloo側のバグでした。
iwadonさん、お付き合い頂きありがとうございました。

**Comment by iwadon** [comment]
あらら、すみませんでした。確認不足です。
少しでもお役に立てたなら良かったです。
追記：Tombloo 0.4.21+Stylish 1.1.1の両方を有効にしてウィンドウが表示されるのを確認しました。ありがとうございました!

**Comment by lunabahamut** [comment]
こちらでもTombloo0.4.21+Stylish1.1.1の両方を有効にして、正常動作を確認しました。
syota氏のスタイルを有効にしても大丈夫でした。
拙い問題報告でしたが、素早い対応ありがとうございました！

またちょっと別の件になってしまうのかもしれないのですが、設定ウインドウを閉じたらFirefox自体のウインドウまで閉じられてしまう問題の他にも、パッチ「shortcutkey.toggleFindBarVisible.js」を使用すると、検索バーがトグルされないどころか、そもそもCtrl＋Fが反応しないという問題も発見しました。
参考になれば幸いです。

**Comment by to** [comment]
ありゃりゃ。shortcutkey.toggleFindBarVisible.js、僕の環境では動作してます。
まだ何かあるのかなあ。

**Comment by to** [comment]
トグルの件、ふつーに再現しました…。一度表示してからテストしちゃってました。

https://github.com/to/tombloo/blob/master/patches/shortcutkey.toggleFindBarVisible.js

**Comment by lunabahamut** [comment]
shortcutkey.toggleFindBarVisible.js、正常動作しました。
ありがとうございます！
