### ISSUE TITLE
二回設定画面を閉じるとFirefox自体が終了する

### ISSUE THREAD

**Issue by smellman** [to/tombloo#22]
Firefox 4.0 (Mac OS X 10.6) において、二回設定画面を閉じるとFirefox自体が終了するという現象が発生します。

再現方法は以下の手順です。
1. メニュー → ツール → Tombloo → Tomblooの設定 を開く
2. Tombloo の設定画面が開くので Window を閉じる
3. 1. と同じ手順で Tombloo の設定画面を開く
4. 再度 Window を閉じる

インストールしている拡張機能は Tombloo 0.4.22 のみです(専用プロファイルを作成して確認)
unloadで処理してるのが問題なのかなとコードみて思ってるんですが、まだ未検証です

**Comment by YungSang** [comment]
私のところでも発生しております。
Firefox 5.0.1/Mac OS X 10.6.8

**Comment by to** [comment]
コンテキストのリロード処理を非同期にしました。
これで解決すると思うのですが…。
ダメなら再オープンしてください。

https://github.com/to/tombloo/commit/82e66cac397ef0cb25ef509b272b7556859ccd54
