### ISSUE TITLE
はてなフォトライフに投稿できていない件

### ISSUE THREAD

**Issue by tobynet** [to/tombloo#3]
画像の”Photo”や"Photo capture"などで、はてなフォトライフに投稿できません。
- はてなにはログインしています
- 設定にてはてなフォトライフにチェックを入れています
- 投稿時にはてなフォトライフにチェックを入れています
- 投稿時に特にエラーメッセージなどは表示されません

**Comment by Constellation** [comment]
再現しました.
http://www.hatena.ne.jp/my の li.welcome がtypoなのかwelcoeになっていることでgetCurrentUserのuser名取得が失敗しています.
to/tomblooにはmergeされていませんが, commitしたのをtoさんに送っておきます.
Constellation/tombloo@cf15e6b9dea265c8792ed6aa9962c7ce07bf9070

**Comment by tobynet** [comment]
おお！ありがとうございます！助かります！

**Comment by to** [comment]
直ってるの確認しました。
Constellationさん、ありがとう。
