### ISSUE TITLE
livedoorクリップに追加できない

### ISSUE THREAD

**Issue by iwadon** [to/tombloo#30]
Share - Link でlivedoorクリップへ登録したところ、エラーは出ませんがlivedoorクリップには何も登録されませんでした。
今のところ100%再現します。また、エラーコンソールには関連するメッセージは出ていません。
なお、taberarelooで同様のことを行ったところ、こちらは登録できました。

追記:環境は Mac OS X 10.7.1, Firefox 7β, Tombloo 0.4.23 です。

**Comment by to** [comment]
以下で修正しました。

https://github.com/to/tombloo/commit/d711503857cfe8548b1e6f37f02a44223a9cd0eb

serianさんが直してくれました。

http://d.hatena.ne.jp/serian/20110928/p1

**Comment by iwadon** [comment]
修正を確認できました。ご対応ありがとうございました!
