### ISSUE TITLE
Tombloo 0.4.29 でリロードできない

### ISSUE THREAD

**Issue by asiamoth** [to/tombloo#38]
shortcutkey.reloadEnvironment.js でリロードしながらオレオレ patch 作りに勤しんでいましたが、最近になって（0.4.29 から？）リロードできなくなりました。Firefox の再起動では patch が反映されます。
環境は以下の通りで、Firefox のプロファイル作り直し・余分な拡張機能とパッチの削除でも状況変わらずでした。
- Tombloo 0.4.29
- Firefox 12.0
- Windows XP

お手すきの時に、できれば確認をお願いします！

**Comment by to** [comment]
スクリプトは正常に終了しているのに環境が更新されてないですね…。

**Comment by to** [comment]
スクリプトロードをevalを経由しないように変更した所直ったみたいです。
いつもありがとうございます。

https://github.com/to/tombloo/commit/b80691191d2c9230bcdf59f74d56c70212b4d59a

**Comment by asiamoth** [comment]
おお、Tombloo の本体を更新すると、見事にリロード可能になりましたよ！
ご対応いただき、ありがとうございました！

**Comment by to** [comment]
よかったですー。
