### ISSUE TITLE
Fx再起動時にウィンドウが最大化されない

### ISSUE THREAD

**Issue by borekina** [to/tombloo#39]
はじめまして。
Tomblooを愛用させて頂いております。

普段、Fxのウィンドウを常に最大化した状態で使用しているのですが、Fxのウィンドウを最大化した状態で再起動すると、
Fxのウィンドウが最大化されない状態で起動する現象が発生しています。
Tombloo単体では問題ありませんが、Element Hiding Helper for Adblock Plusと併用すると必ず発生します。
Tombloo側で対処可能でしょうか？

宜しくお願い致します。

【環境】
Windows 7 SP1 (x86|x64)
Firefox 14.0.1
Tombloo 0.4.30
Adblock Plus 2.1.2
Element Hiding Helper for Adblock Plus 1.2.3

【再現手順】
1. 新規プロファイルを作成してFxを起動
2. 右上の最大化ボタンでFxのウィンドウを最大化
3. Tombloo 0.4.30をインストール
4. Fxを再起動←問題なく（最大化された状態で）起動
5. Adblock Plus 2.1.2とElement Hiding Helper for Adblock Plus 1.2.3をインストール
6. Fxを再起動←ウィンドウが最大化されない状態で起動
7. 右上の最大化ボタンでFxのウィンドウを最大化
8. アドオンマネージャでElement Hiding Helper for Adblock Plusを無効化
9. Fxを再起動←問題なく（最大化された状態で）起動

**Comment by to** [comment]
調べても正確な原因わからなかったのですが、初期化処理を後回しにすることで回避できそうでした。

**Comment by borekina** [comment]
返信が遅くなり、申し訳ございません。
お忙しい中、調査して頂きありがとうございました。

他のアドオンとのコンフリクトは厄介な問題ですよね（；´∀｀）
