### ISSUE TITLE
タグ補完でdeliciousを選んでいると、画像の投稿時に「ログインしていません」と言われタグ補完ができない

### ISSUE THREAD

**Issue by tobynet** [to/tombloo#4]
設定にて、タグの取得先をdeliciousを選んでいると、「ログインしていません」と言われる。
- deliciousにはログインしている
- 画像の投稿時に「ログインしていません」と言われた場合、タグ補完ができない
- 通常の画像以外の投稿では、エラーはでず、タグ補完はできる
- かなり前のバージョンからのようです

**Comment by to** [comment]
すいません、これ再現しません。
僕はタグ取得先deliciousで、ずっと使ってますけど遭遇したことありません。
何か、条件とかありますか?

**Comment by tobynet** [comment]
最近は調子がよいようです。実は特にトラブルになってません。すいません報告が遅れました。

deliciousやflickrはたまにエラー(内容失念)になったりするようですが、しばらくするとまた投稿できるようになるみたいです。
一時的な鯖落ちだったかタイミングが悪かったのか、通信環境が変わったせいかもしれません。

**Comment by tobynet** [comment]
Closedにしてもらってかまわないと思います…

**Comment by to** [comment]
すいません…、遅くなっちゃって。
それでは閉めまーす。
