### ISSUE TITLE
Tombloo.Service.check() の XPath について

### ISSUE THREAD

**Issue by 958** [to/tombloo#40]
いつも便利に使わせていただいてます。
ctx.target にリンクエレメントを指定して Tombloo.Service.check() をコールした際に ctx.target 自身のリンク先が 'Photo - image link' 等の対象にならない為、ctx.link を取得する XPath を './ancestor::a' から './ancestor-or-self::a' に変更したほうが良いと思うのですがいかがでしょうか?
ご検討よろしくお願いします。

**Comment by to** [comment]
直したい! 直します!
具体的に困るページ教えて頂けますか?

**Comment by 958** [comment]
早速の修正ありがとうございます!
具体的な挙動ですが、画像へのテキストリンク上でマウスショートカットによるクイックポストをした場合に './ancestor::a' の場合は現在表示中のページを 'Link' ポストしますが、 './ancestor-or-self::a' の場合はマウスカーソルが乗ったリンクを 'Photo - image link' ポストします。
よろしくお願いします。

**Comment by 958** [comment]
すみません。ページURLを張り忘れました。
たとえば下記ページ内のテキストリンクをポスト対象にしたときになります。
http://himasoku.com/archives/51735316.html

**Comment by to** [comment]
テキストで画像がリンクされているのを考えていませんでした…。
ありがとうございます。
