### ISSUE TITLE
Pinterestのサポート

### ISSUE THREAD

**Issue by take-cheeze** [to/tombloo#45]
TaberarelooではPinterestへのポストが可能で，重宝していたんですが，tomblooでは見当たりません．
tomblooでのサポートは可能でしょうか？

**Comment by to** [comment]
アカウントが無かったので動作確認できなかったのですが招待制じゃなくなってたんですね。
チェックしてみますー。

**Comment by take-cheeze** [comment]
古いissueなのでcloseします
