### ISSUE TITLE
Tumblrの投稿仕様変更でエラーになる

### ISSUE THREAD

**Issue by array** [to/tombloo#49]
Tumblr側の投稿の仕様が変わったようで、以下のエラーになります。
ポストエラー
Tumblr:
src is null
file : 01_utility.js
line : 1862
columnNumber : 0

(Firefox 19 beta Tombloo 0.4.33)

**Comment by to** [comment]
とりあえず暫定応急パッチを当ててコミットしました。確認したところ、とりあえず、全て動作するようです。
拡張の更新から取得できると思います。
