### ISSUE TITLE
Latest Tombloo (Jan 08, 2010 ver) is truncated at the bottom of the post window.

### ISSUE THREAD

**Issue by stv-tribute** [to/tombloo#5]
Hi there,

I encountered two issues on Firefox 3.5.5 with Mac OS X 10.5.8.
However, I don't check it on other environments.

==== Issue1 ====
Post window is truncated at the bottom of the window.

Steps:
1. Do the right click on a image.
2. [Share...] /  [Photo](Then, the post window will be shown.)
3. Observe the bottom of the post window.

==== Issue2 ====
The display size of the thumbnail image is minimized on post window.

Step:
1. Open a post window of a Photo.
2. Change the window size.
  (Then, the thumbnail image will be minimized.)

regards.

**Comment by to** [comment]
OK. I'll fix it.

**Comment by to** [comment]
-moz-box-sizing: content-box;が効いて + 不必要なリサイズ命令の繰り返しで発生してたみたいです。
修正パッチで再現しなくなったとのことでクローズします。
よかったよかった。
