### ISSUE TITLE
展開されない

### ISSUE THREAD

**Issue by shnichkmt** [to/tombloo#50]
postするblogを選んだりパッチを当てるためには、
右クリックでポップアップを出して展開すると思うのですが、
それがなぜかできなくなってしまいました。

右上に小さな四角が出現するだけです。
言葉では説明しがたいので、画像を添付いたしました。

![notworking](https://f.cloud.github.com/assets/3440132/118802/489ddc86-6c89-11e2-9bab-a59011cccb02.jpg)

画像ではカーソルが出ていませんが、実際には上から2番目のShareのところに
カーソルを合わせています。
アドオンを全部オフにしても変わらず、またVer.17.0.2にしても変わりません。

お忙しい中恐縮ですが、ご対応いただけますと幸いです。
よろしくお願いいたします。

**Comment by to** [comment]
起動途中、かなり初期にエラーが出てると思います。
Ctrl + Shift + Jでエラーコンソールを表示し、エラーメッセージが確認できるかもしれません。
ただかなり早い時点で失敗してると、表示できないです。
about:configでtomblooがつく設定をリセットして直るかもしれません。

**Comment by to** [comment]
新しいプロファイルに移行できたら、それを試すのもありです。

**Comment by to** [comment]
パッチを、一度全て無くしてテストするのもいいですね。

**Comment by shnichkmt** [comment]
プロファイルを新しく作ってみたところ、問題は解消されました。
早速のご対応ありがとうございました。

**Comment by to** [comment]
よかったです。
本当なら、ちゃんと原因を確かめて、他の人で起きないようにするとかしないといけないんですけど。
