### ISSUE TITLE
Firefox 3.6RC1でインストール可能だが機能しない

### ISSUE THREAD

**Issue by array** [to/tombloo#6]
Tombloo 0.4.6で、表題通りなのですが、インストールは互換性チェックも通ってしまい、インストールはできます。
エラーは
ポストエラー
  lineNumber : 2496
  message : missing : after property id
  fileName : tombloo.js-> 20_model.js

元ページ: 
  Issues - to/tombloo - GitHub
  http://github.com/to/tombloo/issues

と黄色い画面がでます（Githubの左上のロゴをQuoteでTumblrにポストしようとした場合）

**Comment by armaniacs** [comment]
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; ja; rv:1.9.2pre) Gecko/20100109 Namoroka/3.6pre で使えています．
待てば反映されるかもしれませんね．

**Comment by to** [comment]
こんにちは。
該当箇所は設定から値を呼び出す場所で、ここで失敗しているようです。
about:configで、extensions.tombloo.postConfigの値をリセットしたりして試してみましたが再現しませんでした。
tombloo-prefs.js(初期設定値が書かれている)も破損していないようです。
もしかしたら何かのタイミングで、お試しの環境のprefsが破損してしまったのかもしれません。

**Comment by to** [comment]
arrayさん、プロファイルを作り直したら直ったとのことなのでクローズします。
