### ISSUE TITLE
Evernoteへのポスト時に改行がなくなってしまう件

### ISSUE THREAD

**Issue by tobynet** [to/tombloo#8]
Evernoteへのポスト時に改行がなくなってしまい崩れてしまうのがなんとかならないものでしょうか？

**Comment by to** [comment]
ここらへんの一連のHTMLフレーバー修正で対応。
Linkタイプフルページクリップとかもできるようになった。

http://github.com/to/tombloo/commit/c4350220750b04a4ba256c20e9325f275d6c2d75

TumblrへのQuoteもHTMLになった…。
ちゃんと動くのかこれから試用。

**Comment by tobynet** [comment]
0.4.7にアップデートいたしました。対応ありがとうございます！

Linkに関してはEvernoteでフルにクリップできることを確認しました。
(ページによっては文字化け等はあるみたいですが、これはまた別件で…)

ただ、私の環境ではTumblr、EvernoteともにQuoteでHTMLでどうもクリップできないみたいです。改行などはないままになりましたです。

もう少し試して状況を確認してみます。

**Comment by to** [comment]
再確認してみましたが大丈夫でした。
問題となるページと箇所があると直るかもしれません。
あと、引用してフォームを表示し、編集するとプレーンなテキストのみになってしまいます…。

**Comment by tobynet** [comment]
> あと、引用してフォームを表示し、編集するとプレーンなテキストのみになってしまいます…。

ああ！なるほど。気づきませんでした。まさにそれが原因のようです！
弄ってはいけないんですね。なるほど…
よくテキストを編集することがあったので、そのせいです。

しばらくは意識して動作確認してみますが、多分これで一旦は解決できそうです。
ありがとうございました！

**Comment by to** [comment]
リッチテキストエディタにして、HTMLとプレーンを行き来できるようになるといいんですけど…。
別イシューで。
