### ISSUE TITLE
タグ補完で出せない漢字がある件

### ISSUE THREAD

**Issue by tobynet** [to/tombloo#9]
「社会」をsya、「宗教」をsyuなどの漢字のタグを打鍵しても補完されない

**Comment by to** [comment]
これバグっぽいですね。
たぶん仕様では動きそうです。
タグ名は「社会」や「宗教」そのままですか?
ローマ字変換の部分でエラーになっていそうです。
はっもしかしたらローマ字変換APIの制限回数に達するようになったのかな…。

**Comment by tobynet** [comment]
すいません。「宗教」は出ることを確認しました。それは勘違いでした。

「社会」は出ないみたいです。
他にも特定の感じタグが出ない様ですが、全ては確認出来ていません。
「ma」で「まとめ」とかは出ます。
しかし、「kakusasya」では「格差社会」は出ないようです。
「sya」で何故か「節約」タグがでるのが謎です。「setu」でも「節約」タグは出るようです。

何故か、「sha」では「社会」は出るようでした！しかし「sya」では出ない様です。

deliciousをタグ補完先に使っており、「社会」タグがすでにあるのは確認済みです。
http://delicious.com/toby_net/%E7%A4%BE%E4%BC%9A

けっこうよく使うタグなのでなんとかならないかなー、と思った次第です。
しかし回避策が見つけられましたのでしばらくなんとかなりますｗ　ありがとうございます。

**Comment by to** [comment]
あー漢字をYahooAPIでカタカナに変換した後に独自にローマ字に直してるんですよね。
その変換テーブルの問題だと思います。
とりあえずデフォルトはこれなので、気に入らないところはパッチして変えるかんじです。

http://github.com/to/tombloo/blob/master/xpi/chrome/content/library/01_utility.js#L918

たぶん「格差社会」なら「kkss」みたいに入力して補完させるんだと思います。
特徴マッチなんですよね、だから「節約」も「sya」でいけるという。
